### ISSUE TITLE
agavepy broken in python 3.7

### ISSUE THREAD

**Issue by joestubbs** [TACC/agavepy#113]
**Describe the bug**
In Python 3.7, `async` is a reserved word. The existence of the async.py module in agavepy causes agavepy to not work in Python 3.7.

**To Reproduce**
1. Install agavepy in Python 3.6
2. Try to import it.

**Expected behavior**
agavepy works in python 3.7

**Comment by joestubbs** [comment]
The first step it seems would be to change the name of the `async.py` module to something like `asynchonrous.py`, or something similar. 

The main challenge is that there is client code in the wild that looks like:
```
from agavepy import async
```
or
```
from agavepy.async import AgaveAsyncResponse
```
etc. Of course, there is no hope for the client if they try to upgrade to 3.7. But for earlier python versions, it would be nice to preserve the ability to import using the `async` module name so they don't have to change their code.

To allow these imports to keep working, one possibly might be to try and import the async module in the `__init__.py`, something like:

```
try:
    from agavepy import asynchronous as async
except:
    # will get this in 3.7+
    pass
```
This seems like it should work but it should be tested...

**Comment by jhphan** [comment]
`from agavepy import asynchronous as async` didn't create a permanent alias for the module. This modification to `__init__.py` seemed to work without requiring a try/except block: 

```
import sys

from agavepy import asynchronous
sys.modules['agavepy.async'] = asynchronous
```
