### ISSUE TITLE
Print cURL equivalent for commands

### ISSUE THREAD

**Issue by mwvaughn** [TACC/agavepy#115]
**Is your feature request related to a problem? Please describe.**

A popular feature for the Bash CLI is printing the appropriate cURL command to the screen while performing an action. The new Tapis CLI supports this for API commands implemented using the direct `requests` client instead of AgavePy. See the [relevant issue](https://github.com/TACC-Cloud/tapis-cli-ng/issues/190) for details. 

**Describe the solution you'd like**

Extend swaggerpy to optionally print a cURL equivalent to STDERR, controlled by either a property of the `Agave` object or the value of an environment variable.

**Comment by JoshuaUrrutia** [comment]
It's working in some places and not others, here's a non-exhaustive list
Works:
```
tapis systems list
tapis apps list
tapis jobs list
```
doesn't work:
```
tapis files list
tapis jobs show
tapis files mkdir
tapis files delete
tapis files pems list
```
