### ISSUE TITLE
Add support for `grant_type=authorization_code`

### ISSUE THREAD

**Issue by mrhanlon** [TACC/agavepy#14]
I didn't see right away that AgavePy is compatible with getting tokens using the `grant_type=authorization_code`. The `password` grant [appears to be hardcoded](https://github.com/TACC/agavepy/blob/5eedc256aac1f95b9f67eb1c499b6423c4d6ff5e/agavepy/agave.py#L139). It would be nice to be able to specify additional grant types here.

**Comment by joestubbs** [comment]
Yeah, we left the possibility in there. The issue is processing the callback. What were your thoughts?

**Comment by deardooley** [comment]
How could we do that in a thread safe way that didn't introduce dependencies? Is just providing a function to turn a dict of headers into an auth cache sufficient?

--
Rion

----- Reply message -----

**Comment by mrhanlon** [comment]
Yes, I don't think agavepy needs to support walking the Authorization code flow. I think the assumption would be that if you are using `authoritzation_code` you are using it as a library in a larger framework, and therefore would be able to handle walking the flow. But there doesn't seem to be a way to pass agavepy the code, etc., to get a token. Right now I am making the call to `/token` directly with requests.

I think a lot of the use cases that agavepy covers right now are great for "interactive use", e.g. at a python prompt or in a notebook. But using it as a library in a web application, for instance, there are a few quirks. The two that I can think of off-hand are support for additional `grant_type`s and the auto-token refresh. (Right now we are not taking advantage of token refresh, either, because it would result in the token being refreshed without the webapp knowing.)

**Comment by alejandrox1** [comment]
Closing stale issue.
