### ISSUE TITLE
MultiplePostItResponse.properties.result.type invalid

### ISSUE THREAD

**Issue by mrhanlon** [TACC/agavepy#16]
The result type for `MultiplePostItResponse` is `List`, which is invalid. It should be `array`. The same invalid type is also used on `MultipleInternalUserResponse`.

I will submit a PR if I get a chance before someone else gets to it.

**Comment by joestubbs** [comment]
Please hold off because I have a bunch of changes going out today impacting
the resources.json. I can get the these added in there.

**Comment by joestubbs** [comment]
Should be fixed in 0.3.7.
