### ISSUE TITLE
Bring jobs search to parity with CLI functionality

### ISSUE THREAD

**Issue by mrhanlon** [TACC/agavepy#23]
It looks like the jobs search API defined in the swagger is different than the endpoints used by the `jobs-search` CLI command. It looks like the jobs search API here is using an explicit endpoint whereas the CLI is using the list endpoint with query arguments applied to filter results. It would be good to bring the functionality. I'll get a PR together if no one gets to this before me, but I wanted to go ahead and document the issue.

**Comment by joestubbs** [comment]
Hi Matt,

With the 0.3.9 release, you now have the ability to pass a search parameter (type dict) to all get operations in agavepy. For example: `jobs = agave.jobs.list(search={'id.like': id})`
