### ISSUE TITLE
connection timeout behind https proxy

### ISSUE THREAD

**Issue by schristley** [TACC/agavepy#25]
Traceback (most recent call last):
  File "metadata_report.py", line 17, in <module>
    project_uuid=project_uuid
  File "/Volumes/Antibody/Projects/research/immune/code/vdjserver/vdjserver-repair/vdj_repair_common.py", line 49, in getProjectPermissions
    project_permissions = agave.meta.listMetadataPermissions(uuid=project_uuid)
  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 412, in __call__
    resp = with_refresh(self.client, operation)
  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 70, in with_refresh
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 408, in operation
    response = f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/agavepy/swaggerpy/client.py", line 115, in __call__
    data=data, headers=headers, files=files)
  File "/Library/Python/2.7/site-packages/agavepy/swaggerpy/http_client.py", line 208, in request
    verify=self.verify)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(60, 'Operation timed out'))

**Comment by schristley** [comment]
The test script Walter gave in issue #24 will produce a similar traceback:

agavepy task begin
Traceback (most recent call last):
  File "test5.py", line 38, in <module>
    'recursive': True,                                                    
  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 412, in __call__
    resp = with_refresh(self.client, operation)
  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 70, in with_refresh
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 408, in operation
    response = f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/agavepy/swaggerpy/client.py", line 115, in __call__
    data=data, headers=headers, files=files)
  File "/Library/Python/2.7/site-packages/agavepy/swaggerpy/http_client.py", line 208, in request
    verify=self.verify)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(60, 'Operation timed out'))

**Comment by joestubbs** [comment]
Hi Scott,

Exporting HTTPS_PROXY does have the desired result; I used a dummy IP and port where no server is running and verified that agavepy was using it:

```
$ export HTTPS_PROXY="http://10.10.1.10:1080"
$ ipython
In [1]: from agavepy.agave import Agave

In [2]: ag = Agave.restore(tenant_id='public')

# issue keyboard interrupt since process is hanging, as expected
KeyboardInterrupt: 

In [3]: %debug
ipdb> u
> /home/jstubbs/virtualenvs/agavepy-devel/lib/python2.7/site-packages/requests/packages/urllib3/connection.py(139)_new_conn()
    138                 self, "Connection to %s timed out. (connect timeout=%s)" %
--> 139                 (self.host, self.timeout))
    140 

ipdb> self.host
'10.10.1.10'
```

Can you confirm that agavepy is or is not using the proxy IP you need it to use?

**Comment by schristley** [comment]
Hi Joe,

When I use those commands, I get a different error:


>>> ag = Agave.restore(tenant_id='public')

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 251, in restore

    return Agave._restore_client(tenant_id=tenant_id)

  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 232, in _restore_client

    clients = Agave._read_clients()

  File "/Library/Python/2.7/site-packages/agavepy/agave.py", line 226, in _read_clients

    with open(Agave.agpy_path()) as agpy:

TypeError: coercing to Unicode: need string or buffer, NoneType found

However, I tried the command in our python script and got this info:


ipdb> u

> /home/s166813/.local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py(139)_new_conn()

    138                 self, "Connection to %s timed out. (connect timeout=%s)" %

--> 139                 (self.host, self.timeout))

    140


ipdb> p self.host

'vdj-agave-api.tacc.utexas.edu'

Our script is explicitly setting  the setting the full set of parameters when creating the Agave object, so the host above is pointing to what we specify as the api_server.


    agave = Agave(

        api_server = api_server,

        username = username,

        password = password,

        client_name = client_name,

        api_key = api_key,

        api_secret = api_secret

    )

**Comment by joestubbs** [comment]
It's expected that the restore command (i.e. `ag = Agave.restore(tenant_id='public')`) would fail for you unless you had written client details to a .agpy file (or used the helper method in the library for doing this). `Agave.restore()` is just a convenience method for creating the client from details persisted to a file and shouldn't impact this issue. 

I think the fact that `self.host` is showing up as `vdj-agave-api.tacc.utexas.edu` in urllib means the environment variable isn't being set or isn't available in the session because I am able to see a different host from the api_server variable. For instance, moving up a bit further in the exception stack to the agavepy constructor itself, I see:

```
ipdb> u
> /home/jstubbs/github-repos/agavepy-mast/agavepy/agave.py(212)__init__()
    211         if self.api_key is not None and self.api_secret is not None and self.jwt is None:
--> 212             self.set_client(self.api_key, self.api_secret)
    213         self.clients_resource = None

ipdb> l
    207         if (self.client_name is not None
    208                 and self.api_key is None and self.api_secret is None):
    209             self.api_key, self.api_secret = recover(self.client_name)
    210         self.token = None
    211         if self.api_key is not None and self.api_secret is not None and self.jwt is None:
--> 212             self.set_client(self.api_key, self.api_secret)
    213         self.clients_resource = None
    214         self.all = None
    215         self.refresh_aris()
    216 
    217     def to_dict(self):

ipdb> self.api_server
u'https://public.agaveapi.co'
```

even though `self.host` in urllib has value `10.10.1.10`

**Comment by joestubbs** [comment]
@schristley: might be worth a sanity check from within your ipython session; e.g.

```
In [14]: ! env| grep HTTPS
HTTPS_PROXY=http://10.10.1.10:1080
```

**Comment by schristley** [comment]
Yep


In [16]: ! env | grep HTTPS

HTTPS_PROXY=https://proxy.swmed.edu:3128/

Not sure if there is a public HTTPS proxy that you can test with, or if there is some additional debugging I can do for you?  I'm not very familiar with python unfortunately.

Scott

**Comment by schristley** [comment]
If I go up the stack to the client call, the uri is showing the api server as well, not sure if this is your code:


> /home/s166813/.local/lib/python2.7/site-packages/agavepy/swaggerpy/client.py(135)__call__()

    134                 method, uri, params=params,

--> 135                 data=data, headers=headers, files=files)

    136


ipdb> uri

u'https://vdj-agave-api.tacc.utexas.edu/meta/v2/data/2941877917078655461-242ac1113-0001-012/pems'

**Comment by joestubbs** [comment]
Can you go up the stack to check inside requests for the proxies setting?

```
> /home/jstubbs/virtualenvs/agavepy-devel/lib/python2.7/site-packages/requests/sessions.py(464)request()
    463         send_kwargs.update(settings)
--> 464         resp = self.send(prep, **send_kwargs)
    465 

ipdb> l
    459         send_kwargs = {
    460             'timeout': timeout,
    461             'allow_redirects': allow_redirects,
    462         }
    463         send_kwargs.update(settings)
--> 464         resp = self.send(prep, **send_kwargs)
    465 
    466         return resp
    467 
    468     def get(self, url, **kwargs):
    469         """Sends a GET request. Returns :class:`Response` object.

ipdb> settings
{'verify': False, 'cert': None, 'proxies': {'https': 'http://10.10.1.10:1080'}, 'stream': False}
```

**Comment by joestubbs** [comment]
added proper support in 0.3.10.
