### ISSUE TITLE
File Names in .importData()

### ISSUE THREAD

**Issue by JoshuaUrrutia** [TACC/agavepy#36]
Hi, I don't think destination file names are getting passed. Example:
```
ag.files.importData(filePath='maverick/', systemId='data-tacc-work-urrutia', fileName='Manifest2.yml', fileToUpload=open('Manifest.yml', 'rb'))
```
Uploads a file named Manifest.yml to the storage system, but I would expect it to name the file Manifest2.yml.

**Comment by alejandrox1** [comment]
Fixed by #81
