### ISSUE TITLE
Authentication does not honor AGAVE_CACHEDIR

### ISSUE THREAD

**Issue by mwvaughn** [TACC/agavepy#38]
The Agave Bash CLI supports setting location for the credentials cache via the environment variable `AGAVE_CACHEDIR`.

**Comment by mwvaughn** [comment]
This is severely impacting several folks who dynamically set AGAVE_CACHEDIR as part of continuous integration and testing process, especially now that the develop branch, where a solution had been implemented, is under active development. Can we please fast-track lifting over the function (or even the code) from 4bbe78d2793d6881d05668091175dc492030ecbe into a **released** version of AgavePy please?

**Comment by alejandrox1** [comment]
Closing this. 4bbe78d2793d6881d05668091175dc492030ecbe has already been merged to master.
