### ISSUE TITLE
Using AgavePy to refresh a token maintained outside of AgavePy

### ISSUE THREAD

**Issue by mrhanlon** [TACC/agavepy#4]
This issue is migrated from [Bitbucket](https://bitbucket.org/taccaci/agavepy/issues/14).

When using AgavePy as a library within a larger application (e.g., Django), we persist the user's OAuth token outside of the Agave object, e.g., in the session or in the database. It is useful, then, to be able to test and refresh the token directly without needing to make an additional API call. AgavePy will refresh the token automatically when an API call fails due to expired token, but this then results in two API calls, the response of which we don't need at all.

In Django we have an application/authentication backend that walks the authorization code flow to get a token and then calls the /profiles API to validate the token and get the user profile to determine the user's identity. Upon success we persist the token in the session. Later, we need to refresh the token when it expires. This is relatively easy to do using requests, but the preference would be to be able to instantiate an instance of `agavepy.agave.Token` and call `token.refresh()` directly to retrieve a new token.

Here is what we are doing now. When we get a token (at login) we record with it the time of retrieval. Later, in a Django middleware class, we hook `process_request` to 1) to see if the token is still valid and if not, 2) refresh the token:

```python
class _AgaveStub(object):
    """
    A stub class to mimic the Agave object that is typically the "parent" of
    agavepy.agave.Token
    """

    def refresh_aris(self):
        pass

class AgaveTokenRefreshMiddleware(object):

    def process_request(self, request):
        if request.path != '/logout/':
            token_key = getattr(settings, 'AGAVE_TOKEN_SESSION_ID')
            if token_key in request.session:
                current_time = time.time()
                token = request.session[token_key]
                valid_seconds = token['created'] + token['expires_in'] - current_time
                if valid_seconds <= 0:
                    logger.debug('refreshing current token: %s' % token)
                    agave_token = Token(None, None,
                        getattr(settings, 'AGAVE_TENANT_BASEURL'),
                        getattr(settings, 'AGAVE_CLIENT_KEY'),
                        getattr(settings, 'AGAVE_CLIENT_SECRET'), True, _AgaveStub())
                    agave_token.token_info = {'refresh_token': token['refresh_token']}
                    agave_token.refresh()
                    agave_token.token_info['created'] = current_time
                    logger.info('refreshed token: %s' % agave_token.token_info)
                    request.session[token_key] = agave_token.token_info
                    request.session.save()
                else:
                    logger.debug('session.%s valid for %s additional seconds: %s' %
                        (token_key, valid_seconds, token))


```

We end up having to mock the `agavepy.agave.Agave` class, which `Token` expects to be it's `parent` attribute. We also need to manually set the `token_info` after instantiating the Token because there isn't a way to pass the `refresh_token` in the constructor. This works fine, but it is certainly not ideal.

It would be great if we could instantiate a Token efficiently and independently of the rest of AgavePy.

**Comment by joestubbs** [comment]
Matt,

You can create a client with the minimal set of parameters required by the OAuth spec and refresh the token using the refresh() method; i.e.,

```
ag = Agave(api_server=base, api_key=key, api_secret=secret, token=token, refresh_token=refresh_token, verify=False)
ag.token.refresh()
```

Does that meet your requirements?

**Comment by mrhanlon** [comment]
Hmm, it should. I will check it out.

**Comment by mrhanlon** [comment]
Yes, this works fine. I don't know why I missed that before. Thanks.
