### ISSUE TITLE
Typos on documentation

### ISSUE THREAD

**Issue by alejandrox1** [TACC/agavepy#76]
The documentation is available on https://agavepy.readthedocs.io/en/latest/
The source is in [docs/docsite](https://github.com/TACC/agavepy/tree/develop/docs/docsite)
Some typos already found:

1. [About Agavepy](https://agavepy.readthedocs.io/en/latest/index.html) - AgavePy is a client that will allow you to script your `interacttion`
2. [Installation guide](https://agavepy.readthedocs.io/en/latest/docsite/installation_guide/installation.html) - In this guide `wewill`
3. [What version to install](https://agavepy.readthedocs.io/en/latest/docsite/installation_guide/installation.html) - Some features may be missing from `ofifical`

**Comment by belushkin** [comment]
I can do it

**Comment by belushkin** [comment]
Where can I find this documentation?

**Comment by alejandrox1** [comment]
Hi @belushkin , thank you for volunteering to help out. I updated the initial comment, it should give you all the info related to the documentation. For information regarding how to make the changes see [CONTRIBUTING](https://github.com/TACC/agavepy/blob/develop/CONTRIBUTING.md).

**Comment by belushkin** [comment]
I will do it today @alejandrox1
