### ISSUE TITLE
Add ag.apps.list() flag for raw JSON?

### ISSUE THREAD

**Issue by jturcino** [TACC/agavepy#8]
I am trying to print ag.apps.list() using json.dumps; however, the datetime formate of the lastModified time is not json serializable. Would it be possible to add a flag to ag.apps.list() such that the raw JSON is not modified (and thus lastModified time is not in datetime format) before output? For example, apps.list(--raw)

An example of the datetime error is below. Note: I did not include the full list of apps after ```print apps```. If the full list would be helpful, please let me know!
```
>>> from agavepy.agave import Agave
>>> ag = Agave(api_server = 'https://vdj-agave-api.tacc.utexas.edu', token = '***')
>>> apps = ag.apps.list()
>>> print apps
[{u'name': u'jturcino-samtools-sort', u'lastModified': datetime.datetime(2015, 11, 19, 17, 31, 56, tzinfo=tzoffset(None, -21600)), u'isPublic': False, u'label': u'SAMtools sort', u'executionSystem': u'stampede-11112015-1156-jturcino', u'version': u'0.1.19', u'_links': {u'self': {u'href': u'https://vdj-agave-api.tacc.utexas.edu/apps/v2/jturcino-samtools-sort-0.1.19'}}, u'shortDescription': u'Sort a BAM file by name or coordinate', u'id': u'jturcino-samtools-sort-0.1.19', u'revision': 3}, {u'name': u'igblast-lonestar', u'lastModified': datetime.datetime(2015, 11, 13, 17, 6, 18, tzinfo=tzoffset(None, -21600)), u'isPublic': True, u'label': u'igblast', u'executionSystem': u'lonestar.tacc.utexas.edu', u'version': u'1.4.0', u'_links': {u'self': {u'href': u'https://vdj-agave-api.tacc.utexas.edu/apps/v2/igblast-lonestar-1.4.0u7'}}, u'shortDescription': u'IgBLAST on Lonestar4', u'id': u'igblast-lonestar-1.4.0u7', u'revision': 7}, {u'name': u'igblast-ls4extended', u'lastModified': datetime.datetime(2015, 10, 30, 13, 59, 32, tzinfo=tzoffset(None, -18000)), u'isPublic': True, u'label': u'igblast', u'executionSystem': u'lonestar.tacc.utexas.edu', u'version': u'1.4.0', u'_links': {u'self': {u'href': u'https://vdj-agave-api.tacc.utexas.edu/apps/v2/igblast-ls4extended-1.4.0u1'}}, u'shortDescription': u'IgBLAST on Lonestar4', u'id': u'igblast-ls4extended-1.4.0u1', u'revision': 1}]
>>> print json.dumps(apps, sort_keys = True, indent = 4, separators = (',', ': '))
Traceback (most recent call last):
  File "./vdj-apps-list.py", line 34, in <module>
    print json.dumps(apps, sort_keys = True, indent = 4, separators = (',', ': '))
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2015, 11, 19, 17, 31, 56, tzinfo=tzoffset(None, -21600)) is not JSON serializable```

**Comment by deardooley** [comment]
Are you asking for the raw ISO 8601 string rather than a datetime object you could deserialize as you see fit? Would you still expect it in ISO 8601 format or resolved against the current timezone? Are there other fields you expect to be "raw?"  Would this snippet work for you?


from datetime import datetime

def json_serial(obj):
    """JSON serializer for objects not serializable by default json code"""

    if isinstance(obj, datetime):
        serial = obj.isoformat()
        return serial
    raise TypeError ("Type not serializable")
from datetime import datetime
from json import dumps

print dumps(datetime.now(), default=json_serial)
credit: http://stackoverflow.com/a/22238613/1689205 <http://stackoverflow.com/a/22238613/1689205>


—
Rion

**Comment by deardooley** [comment]
Are you asking for the raw ISO 8601 string rather than a datetime object you could deserialize as you see fit? Would you still expect it in ISO 8601 format or resolved against the current timezone? Are there other fields you expect to be "raw?"  Would this snippet work for you?

```python
from datetime import datetime

def json_serial(obj):
    """JSON serializer for objects not serializable by default json code"""

    if isinstance(obj, datetime):
        serial = obj.isoformat()
        return serial
    raise TypeError ("Type not serializable")
```

```python
from datetime import datetime
from json import dumps

print dumps(datetime.now(), default=json_serial)
```
credit: [http://stackoverflow.com/a/22238613/1689205](http://stackoverflow.com/a/22238613/1689205)

**Comment by jturcino** [comment]
That snippet works wonderfully! Thank you very much!

**Comment by joestubbs** [comment]
Thanks @deardooley, this is a decent work around. If there is demand, agavepy could look for a "raw" parameter to any method and conditionally bypass the post_process() method in the Operation class. For now I will close out this issue.
